### Get tasks
GET http://localhost:8080/api/tasks

###
POST http://localhost:8080/api/capture-the-flag
Content-Type: application/json
#Authorization: Basic dGVzdDp0ZXN0
#Cookie: SESSION=e42676fc-0ba1-4150-8879-76918949db40

{
  "flag": "flag-{U1RFR0FOTw==10qwerty}"
}

###
POST http://localhost:8080/public/login
Content-Type: application/json
Authorization: Basic dGVzdDp0ZXN0

###
GET http://localhost:8080/public/login/isAuthenticated
Content-Type: application/json

###
POST http://localhost:8080/api/admin/admintask
Content-Type: application/json